inherit_from: .rubocop_todo.yml

AllCops:
  TargetRubyVersion: 3.0
  NewCops: enable
  SuggestExtensions: false
  
Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  EnforcedStyle: double_quotes

Naming/MethodParameterName:
  AllowedNames: s, r, d

Metrics/MethodLength:
  Exclude:
    - 'test/**/test_*.rb'